{
 "title": "Host Inspection",
 "time": { "from": "2018-09-18T17:14:52.000Z", "to": "2020-09-21T17:01:01.000Z" },
 "templating": {
  "list": [
   {
    "name": "scan",
    "label": "Scan Name",
    "query": "SELECT DISTINCT name\nFROM nessus_scans_info\nWHERE scan_start > '2020-01-01 00:00:00'"
   },
   {
    "name": "host",
    "label": "Hostname",
    "query": "SELECT DISTINCT host\nFROM nessus_report nr\nINNER JOIN nessus_scans_info nsi ON nr.history_id = nsi.history_id\nWHERE nsi.name = '$scan'"
   },
   {
    "name": "scan_time",
    "label": "Scan Time",
    "query": "SELECT\n    scan_start\nFROM nessus_scans_info\nWHERE history_id IN (SELECT DISTINCT history_id FROM nessus_report WHERE host = '$host')\n    AND hosts LIKE '%$host%';"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "stat",
   "description": "This is a summary of the selected hosts most recent scan. ",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    critical,\n    high,\n    medium,\n    low,\n    info\nFROM nessus_scans_host_metric shm\nINNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\nWHERE shm.history_id = (SELECT DISTINCT shm.history_id FROM nessus_report WHERE host = '$host' ORDER BY history_id DESC LIMIT 1)\n    AND hostname = '$host'\n    AND scan_start = '$scan_time'"
    }
   ]
  },
  {
   "title": "Vulnerabilities List",
   "type": "table",
   "description": "A comprehensive list of vulnerabilities detected in the most recent scan ordered from highest to lowest risk.",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    name,\n    risk,\n    COUNT(name)\nFROM nessus_report nr\nWHERE history_id = (SELECT history_id FROM nessus_scans_info WHERE hosts LIKE '%$host%' AND scan_start = '$scan_time')\n    AND host = '$host'\nGROUP BY risk, name\nORDER BY risk, name"
    }
   ]
  },
  {
   "title": "Vulnerabilities by Severity",
   "type": "graph",
   "description": "This is the amount of vulnerabilities by severity detected over a period of time for an individual host.",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    high,\n    medium,\n    low,\n    info,\n    scan_start AS time\nFROM nessus_scans_host_metric shm\nINNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\nWHERE hostname = '$host'\nORDER BY scan_start ASC"
    }
   ]
  }
 ]
}