{
 "title": "Scan Compare",
 "time": { "from": "2018-11-27T10:27:44.000Z", "to": "2020-09-15T11:50:22.000Z" },
 "templating": {
  "list": [
   {
    "name": "scan_name",
    "label": "Scan Name",
    "query": "SELECT DISTINCT name\nFROM nessus_scans\nWHERE enabled = true;"
   },
   {
    "name": "scan_time_1",
    "label": "Scan 1 - Time",
    "query": "SELECT\n    scan_start\nFROM nessus_scans_info nsi\n         INNER JOIN nessus_scans ns ON nsi.scan_id = ns.scan_id\n         INNER JOIN nessus_scans_history nsh ON nsi.history_id = nsh.history_id\nWHERE ns.name = '$scan_name'\n  AND is_csv_imported = TRUE\n  AND (nsh.is_empty = FALSE OR nsh.is_empty IS NULL)"
   },
   {
    "name": "scan_time_2",
    "label": "Scan 2 - Time",
    "query": "SELECT scan_start\nFROM nessus_scans_info nsi\nINNER JOIN nessus_scans ns ON nsi.scan_id = ns.scan_id\nINNER JOIN nessus_scans_history nsh ON nsh.history_id = nsi.history_id\nWHERE ns.name = '$scan_name' AND scan_start < '$scan_time_1'\nAND is_csv_imported = TRUE\nAND (nsh.is_empty = FALSE OR nsh.is_empty IS NULL)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "content": "# SCAN 1" },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(critical)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_1';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(high)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_1';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(medium)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_1';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(low)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_1';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(info)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_1';"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "options": { "content": "# SCAN 2" },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(critical)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_2';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(high)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_2';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(medium)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_2';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(low)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_2';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(info)\nFROM nessus_scans_host_metric shm\n         INNER JOIN nessus_scans_info nsi ON shm.history_id = nsi.history_id\n         INNER JOIN nessus_scans ns ON ns.scan_id = nsi.scan_id\nWHERE ns.name = '$scan_name' AND scan_start = '$scan_time_2';"
    }
   ]
  },
  {
   "title": "Vulnerabilities by Severity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    SUM(critical) AS critical,\n    SUM(high) AS high,\n    SUM(medium) AS medium,\n    SUM(low) AS low,\n    SUM(info) AS info,\n    scan_start AS time\nFROM nessus_scans_host_metric nshm\nINNER JOIN nessus_scans_info nsi ON nshm.history_id = nsi.history_id\nINNER JOIN nessus_scans ns ON nsi.scan_id = ns.scan_id\nWHERE ns.name = '$scan_name'\nGROUP BY scan_start\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "New Vulnerabilities",
   "type": "table",
   "description": "All new vulnerabilities detected in scan 1 that was not detected in scan 2.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH scan_1 AS (\n    SELECT\n--         *\n        COUNT(DISTINCT nr.name) AS total,\n            risk,\n            nr.name,\n            host\n    FROM nessus_report nr\n        INNER JOIN nessus_scans_info nsi ON nr.history_id = nsi.history_id\n        INNER JOIN nessus_scans ns ON nsi.scan_id = ns.scan_id\n    WHERE ns.name = '$scan_name'\n      AND cve != 'null'\n      AND nsi.scan_start = '$scan_time_1'\n    GROUP BY nr.name, risk, host\n    ORDER BY nr.name\n),\n    scan_2 AS (\n       SELECT COUNT(DISTINCT nr.name) AS total,\n                risk,\n                nr.name\n        FROM nessus_report nr\n            INNER JOIN nessus_scans_info nsi ON nr.history_id = nsi.history_id\n            INNER JOIN nessus_scans ns ON nsi.scan_id = ns.scan_id\n         WHERE ns.name = '$scan_name'\n          AND cve != 'null'\n          AND nsi.scan_start = '$scan_time_2'\n        GROUP BY nr.name, risk\n    ),\n    res_scan_1 AS (\n        SELECT\n            name,\n            SUM(total) AS total,\n            risk\n        FROM scan_1\n        GROUP BY name, risk\n        ORDER BY name\n    ),\n    res_scan_2 AS (\n            SELECT\n            name,\n            SUM(total) AS total,\n            risk\n        FROM scan_2\n        GROUP BY name, risk\n        ORDER BY name\n    )\nSELECT\n    s1.name,\n    s1.risk,\n    s1.total - COALESCE(s2.total, 0) AS total\nFROM res_scan_1 s1\nLEFT JOIN res_scan_2 s2 ON s1.name = s2.name\nWHERE s1.name NOT IN (SELECT sub_s2.name FROM res_scan_2 sub_s2)\n    OR (s1.name = s2.name AND s1.total > s2.total )\nORDER BY risk, name\n;"
    }
   ]
  },
  {
   "title": "Resolved Vulnerabilities",
   "type": "table",
   "description": "All vulnerabilities detected in scan 2 and not detected in scan 1.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH scan_1 AS (\n    SELECT\n--         *\n        COUNT(DISTINCT nr.name) AS total,\n            risk,\n            nr.name,\n            host\n    FROM nessus_report nr\n        INNER JOIN nessus_scans_info nsi ON nr.history_id = nsi.history_id\n        INNER JOIN nessus_scans ns ON nsi.scan_id = ns.scan_id\n--     WHERE ns.name = '$scan_name'\n    WHERE ns.name = 'DN'\n      AND cve != 'null'\n--       AND nsi.scan_start = '$scan_time_1'\n      AND nsi.scan_start = '2020-09-21 17:01:01.000000'\n    GROUP BY nr.name, risk, host\n    ORDER BY nr.name\n),\n    scan_2 AS (\n       SELECT COUNT(DISTINCT nr.name) AS total,\n                risk,\n                nr.name\n        FROM nessus_report nr\n            INNER JOIN nessus_scans_info nsi ON nr.history_id = nsi.history_id\n            INNER JOIN nessus_scans ns ON nsi.scan_id = ns.scan_id\n--         WHERE ns.name = '$scan_name'\n        WHERE ns.name = 'DN'\n          AND cve != 'null'\n--           AND nsi.scan_start = '$scan_time_2'\n          AND nsi.scan_start = '2020-01-13 10:05:08.000000'\n        GROUP BY nr.name, risk\n    ),\n    res_scan_1 AS (\n        SELECT\n            name,\n            SUM(total) AS total,\n            risk\n        FROM scan_1\n        GROUP BY name, risk\n        ORDER BY name\n    ),\n    res_scan_2 AS (\n            SELECT\n            name,\n            SUM(total) AS total,\n            risk\n        FROM scan_2\n        GROUP BY name, risk\n        ORDER BY name\n    )\nSELECT\n-- *\n    s2.name,\n    s2.risk,\n    s2.total - COALESCE(s1.total, 0) AS total\nFROM res_scan_2 s2\nLEFT JOIN res_scan_1 s1 ON s1.name = s2.name\nWHERE s1.name IS NULL\nOR (s2.name = s1.name AND s2.total > COALESCE(s1.total, 0))\nORDER BY s2.risk, name"
    }
   ]
  },
  {
   "title": "Risk Changes",
   "type": "table",
   "description": "All vulnerabilities detected in scan 1 and scan 2 that had a severity change.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH scan_1 AS (\n    SELECT COUNT(nr.name) AS total,\n            risk,\n            nr.name\n    FROM nessus_report nr\n        INNER JOIN nessus_scans_info nsi ON nr.history_id = nsi.history_id\n        INNER JOIN nessus_scans ns ON nsi.scan_id = ns.scan_id\n    WHERE ns.name = '$scan_name'\n      AND cve != 'null'\n     AND nsi.scan_start = '$scan_time_1'\n    GROUP BY nr.name, risk\n    ORDER BY nr.name\n),\n    scan_2 AS (\n       SELECT COUNT(nr.name) AS total,\n                risk,\n                nr.name\n        FROM nessus_report nr\n            INNER JOIN nessus_scans_info nsi ON nr.history_id = nsi.history_id\n            INNER JOIN nessus_scans ns ON nsi.scan_id = ns.scan_id\n        WHERE ns.name = '$scan_name' --AND cve = 'CVE-2015-3411'\n          AND cve != 'null'\n        AND nsi.scan_start = '$scan_time_2'\n        GROUP BY nr.name, risk\n        ORDER BY nr.name\n    )\nSELECT\n    s1.name,\n    s1.risk AS new_risk,\n    s2.risk AS old_risk,\n    s1.total\nFROM scan_1 s1\nLEFT JOIN scan_2 s2 ON s2.name = s1.name\nWHERE s1.risk != s2.risk"
    }
   ]
  }
 ]
}