{
 "title": "Vulnerability Inspection",
 "time": { "from": "2018-11-27T10:27:44.000Z", "to": "2020-09-15T11:50:22.000Z" },
 "templating": {
  "list": [
   {
    "name": "start_year",
    "label": "Start Year",
    "query": "SELECT DISTINCT\n    \"left\"(CAST(scan_start AS VARCHAR), 4) AS filter_months\nFROM nessus_scans_info nsi\nINNER JOIN nessus_scans_history nsh ON nsh.history_id = nsi.history_id\nAND is_imported = true AND is_csv_imported = true\nAND nsi.status = 'completed'\nORDER BY filter_months DESC;"
   },
   {
    "name": "start_month",
    "label": "Starting Month",
    "query": "SELECT DISTINCT\n-- *\n--     \"left\"(CAST(scan_start AS VARCHAR),7) AS scan_start,\n    CAST(substr(CAST(scan_start AS VARCHAR),6,2) AS INT),\n    lv.value\nFROM nessus_scans_info nsi\nINNER JOIN nessus_scans_history nsh ON nsh.history_id = nsi.history_id\nINNER JOIN lookup_values lv ON lv.key = substr(CAST(scan_start AS VARCHAR), 6, 2) AND lv.type_id = (SELECT id FROM lookup_types WHERE name = 'Months' AND deleted = false LIMIT 1)\nWHERE \"left\"(CAST(scan_start AS VARCHAR),4) = '$start_year'\nAND is_imported = true AND is_csv_imported = true\nAND nsi.status = 'completed'\nORDER BY substr DESC"
   },
   {
    "name": "end_year",
    "label": "End Year",
    "query": "SELECT DISTINCT\n    \"left\"(CAST(scan_start AS VARCHAR), 4) AS filter_months\nFROM nessus_scans_info nsi\nINNER JOIN nessus_scans_history nsh ON nsh.history_id = nsi.history_id\nAND is_imported = true AND is_csv_imported = true\nAND nsi.status = 'completed'\nAND CAST(\"left\"(CAST(scan_start AS VARCHAR), 4) AS INT) >= $start_year\nORDER BY filter_months DESC;"
   },
   {
    "name": "end_month",
    "label": "End Month",
    "query": "SELECT DISTINCT\n-- *\n--     \"left\"(CAST(scan_start AS VARCHAR),7) AS scan_start,\n    CAST(substr(CAST(scan_start AS VARCHAR),6,2) AS INT),\n    lv.value\nFROM nessus_scans_info nsi\nINNER JOIN nessus_scans_history nsh ON nsh.history_id = nsi.history_id\nINNER JOIN lookup_values lv ON lv.key = substr(CAST(scan_start AS VARCHAR), 6, 2) AND lv.type_id = (SELECT id FROM lookup_types WHERE name = 'Months' AND deleted = false LIMIT 1)\n-- WHERE \"left\"(CAST(scan_start AS VARCHAR),4) = '$end_year'\nWHERE \"left\"(CAST(scan_start AS VARCHAR),4) = '$end_year'\n-- AND lv.value != '$start_month'\n-- AND lv.id > (SELECT id FROM lookup_values WHERE value = '$start_month')\nAND is_imported = true AND is_csv_imported = true\nAND nsi.status = 'completed'\nORDER BY substr DESC"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Vulnerabilities",
   "type": "stat",
   "description": "This is the total amount of unique vulnerabilities detected for each host between the Primary & Secondary month.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "\nWITH date_time AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'September' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS start_time,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2021', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'February' ORDER BY lv.key DESC), '-', '01 00:1:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS end_time)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$start_year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$start_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS start_time,\n (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$end_year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$end_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS end_time)\n    ),\n    scan_id_total_time AS (\n        SELECT\n--                 row_number()\n--                 OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n        FROM nessus_scans_info\n        WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n        AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT start_time FROM date_time))\n        AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT end_time FROM date_time)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n    )\n\n    ,distinct_vuln_by_host AS (\n         SELECT DISTINCT\n             host,\n             risk,\n             name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT scan_id_total_time.history_id FROM scan_id_total_time))\n    )\n    SELECT COUNT(risk),\n            risk,\n            now() AS TIME\n    FROM distinct_vuln_by_host\n    GROUP BY risk, now()\n    ORDER BY risk;"
    }
   ]
  },
  {
   "title": "Resolved Vulnerabilities",
   "type": "stat",
   "description": "This is the total amount of resolved vulnerabilities since the last scans of the previous month.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- GLOBAL RESOLVED\nWITH primary_time AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    secondary_time AS (\n--         SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'February' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'June' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    new_month AS (\n        SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n        FROM nessus_scans_info\n        WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n        AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM primary_time))\n        AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM primary_time)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n    ),\n    new_result AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT new_month.history_id FROM new_month WHERE new_month.cnt = 1))\n    ),\n    v_new AS (\n        SELECT\n            nr.name,\n            nr.risk,\n            count(nr.name) AS total\n        FROM new_result nr\n        GROUP BY nr.risk, nr.name\n        ORDER BY nr.risk, (count(nr.name)) DESC, nr.name\n    ),\n    old_month AS (\n        SELECT\n            row_number()\n            OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n            nessus_scans_info.scan_id,\n            nessus_scans_info.history_id,\n            nessus_scans_info.scan_start,\n            nessus_scans_info.status\n        FROM nessus_scans_info\n        WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n        AND nessus_scans_info.scan_start >= (date_trunc('month'::TEXT, (SELECT time_1 FROM secondary_time)) - '1 mon'::INTERVAL)\n        AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM secondary_time)) - '1 day'::INTERVAL)\n    ),\n    old_result AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 old_month.history_id\n                                             FROM old_month\n                                             WHERE old_month.cnt = 1))\n    ),\n    v_old AS (\n        SELECT\n            pr.name,\n            pr.risk,\n            count(pr.name) AS total\n        FROM old_result pr\n        GROUP BY pr.risk, pr.name\n        ORDER BY pr.risk, (count(pr.name)) DESC, pr.name\n    )\nSELECT\n    vo.risk,\n    SUM(vo.total - COALESCE(vn.total, 0)) AS total,\n    NOW() AS time\nFROM v_old vo\nLEFT JOIN v_new vn ON vo.name = vn.name\nWHERE vo.name NOT IN (SELECT name FROM v_new)\n    OR (vn.name = vo.name AND vo.total > vn.total)\nGROUP BY vo.risk;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "options": { "content": "# PRIMARY MONTH" },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH v_time_1 AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    new_month AS (\n    SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n    FROM nessus_scans_info\n    WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n      AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM v_time_1))\n      AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM v_time_1)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n),\n     new_results AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 new_month.history_id\n                                             FROM new_month\n                                             WHERE new_month.cnt = 1))\n     ),\n     v_new AS (\n        SELECT\n            cr.name,\n            cr.risk,\n            count(cr.name) AS total\n        FROM new_results cr\n        GROUP BY cr.risk, cr.name\n        ORDER BY cr.risk, (count(cr.name)) DESC, cr.name\n)\nSELECT\n    risk,\n    SUM(total) AS total,\n    NOW() as time\nFROM v_new\nWHERE risk = 'Critical'\nGROUP BY risk;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH v_time_1 AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    new_month AS (\n    SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n    FROM nessus_scans_info\n    WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n      AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM v_time_1))\n      AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM v_time_1)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n),\n     new_results AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 new_month.history_id\n                                             FROM new_month\n                                             WHERE new_month.cnt = 1))\n     ),\n     v_new AS (\n        SELECT\n            cr.name,\n            cr.risk,\n            count(cr.name) AS total\n        FROM new_results cr\n        GROUP BY cr.risk, cr.name\n        ORDER BY cr.risk, (count(cr.name)) DESC, cr.name\n)\nSELECT\n    risk,\n    SUM(total) AS total,\n    NOW() as time\nFROM v_new\nWHERE risk = 'High'\nGROUP BY risk;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH v_time_1 AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = 'September'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = 'September'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    new_month AS (\n    SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n    FROM nessus_scans_info\n    WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n      AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM v_time_1))\n      AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM v_time_1)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n),\n     new_results AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 new_month.history_id\n                                             FROM new_month\n                                             WHERE new_month.cnt = 1))\n     ),\n     v_new AS (\n        SELECT\n            cr.name,\n            cr.risk,\n            count(cr.name) AS total\n        FROM new_results cr\n        GROUP BY cr.risk, cr.name\n        ORDER BY cr.risk, (count(cr.name)) DESC, cr.name\n)\nSELECT\n    risk,\n    SUM(total) AS total,\n    NOW() as time\nFROM v_new\nWHERE risk = 'Medium'\nGROUP BY risk;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH v_time_1 AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    new_month AS (\n    SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n    FROM nessus_scans_info\n    WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n      AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM v_time_1))\n      AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM v_time_1)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n),\n     new_results AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 new_month.history_id\n                                             FROM new_month\n                                             WHERE new_month.cnt = 1))\n     ),\n     v_new AS (\n        SELECT\n            cr.name,\n            cr.risk,\n            count(cr.name) AS total\n        FROM new_results cr\n        GROUP BY cr.risk, cr.name\n        ORDER BY cr.risk, (count(cr.name)) DESC, cr.name\n)\nSELECT\n    risk,\n    SUM(total) AS total,\n    NOW() as time\nFROM v_new\nWHERE risk = 'Low'\nGROUP BY risk;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "options": { "content": "# SECONDARY MONTH" },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nWITH secondary_time AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    old_month AS (\n    SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n    FROM nessus_scans_info\n    WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n      AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM secondary_time))\n      AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM secondary_time)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n),\n     old_results AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 old_month.history_id\n                                             FROM old_month\n                                             WHERE old_month.cnt = 1))\n     ),\n     v_old AS (\n        SELECT\n            cr.name,\n            cr.risk,\n            count(cr.name) AS total\n        FROM old_results cr\n        GROUP BY cr.risk, cr.name\n        ORDER BY cr.risk, (count(cr.name)) DESC, cr.name\n)\nSELECT\n    risk,\n    SUM(total) AS total,\n    NOW() as time\nFROM v_old\nWHERE risk = 'Critical'\nGROUP BY risk;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nWITH secondary_time AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    old_month AS (\n    SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n    FROM nessus_scans_info\n    WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n      AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM secondary_time))\n      AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM secondary_time)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n),\n     old_results AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 old_month.history_id\n                                             FROM old_month\n                                             WHERE old_month.cnt = 1))\n     ),\n     v_old AS (\n        SELECT\n            cr.name,\n            cr.risk,\n            count(cr.name) AS total\n        FROM old_results cr\n        GROUP BY cr.risk, cr.name\n        ORDER BY cr.risk, (count(cr.name)) DESC, cr.name\n)\nSELECT\n    risk,\n    SUM(total) AS total,\n    NOW() as time\nFROM v_old\nWHERE risk = 'High'\nGROUP BY risk;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nWITH secondary_time AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    old_month AS (\n    SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n    FROM nessus_scans_info\n    WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n      AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM secondary_time))\n      AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM secondary_time)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n),\n     old_results AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 old_month.history_id\n                                             FROM old_month\n                                             WHERE old_month.cnt = 1))\n     ),\n     v_old AS (\n        SELECT\n            cr.name,\n            cr.risk,\n            count(cr.name) AS total\n        FROM old_results cr\n        GROUP BY cr.risk, cr.name\n        ORDER BY cr.risk, (count(cr.name)) DESC, cr.name\n)\nSELECT\n    risk,\n    SUM(total) AS total,\n    NOW() as time\nFROM v_old\nWHERE risk = 'Medium'\nGROUP BY risk;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nWITH secondary_time AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'March' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    old_month AS (\n    SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n    FROM nessus_scans_info\n    WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n      AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM secondary_time))\n      AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM secondary_time)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n),\n     old_results AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 old_month.history_id\n                                             FROM old_month\n                                             WHERE old_month.cnt = 1))\n     ),\n     v_old AS (\n        SELECT\n            cr.name,\n            cr.risk,\n            count(cr.name) AS total\n        FROM old_results cr\n        GROUP BY cr.risk, cr.name\n        ORDER BY cr.risk, (count(cr.name)) DESC, cr.name\n)\nSELECT\n    risk,\n    SUM(total) AS total,\n    NOW() as time\nFROM v_old\nWHERE risk = 'Low'\nGROUP BY risk;"
    }
   ]
  },
  {
   "title": "New Vulnerabilities",
   "type": "table",
   "description": "All new vulnerabilities detected in scan 1 that was not detected in scan 2.",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM v_current_month WHERE name NOT IN (SELECT name FROM v_previous_month);"
    }
   ]
  },
  {
   "title": "Resolved Vulnerabilities",
   "type": "table",
   "description": "All vulnerabilities detected in scan 2 and not detected in scan 1.",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH primary_time AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'September' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'September' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    secondary_time AS (\n--         SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'August' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'August' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    new_month AS (\n        SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n        FROM nessus_scans_info\n        WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n        AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM primary_time))\n        AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM primary_time)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n    ),\n    new_result AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT new_month.history_id FROM new_month WHERE new_month.cnt = 1))\n    ),\n    v_new AS (\n        SELECT\n            nr.name,\n            nr.risk,\n            count(nr.name) AS total\n        FROM new_result nr\n        GROUP BY nr.risk, nr.name\n        ORDER BY nr.risk, (count(nr.name)) DESC, nr.name\n    ),\n    old_month AS (\n        SELECT\n            row_number()\n            OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n            nessus_scans_info.scan_id,\n            nessus_scans_info.history_id,\n            nessus_scans_info.scan_start,\n            nessus_scans_info.status\n        FROM nessus_scans_info\n        WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n        AND nessus_scans_info.scan_start >= (date_trunc('month'::TEXT, (SELECT time_1 FROM secondary_time)) - '1 mon'::INTERVAL)\n        AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM secondary_time)) - '1 day'::INTERVAL)\n    ),\n    old_result AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 old_month.history_id\n                                             FROM old_month\n                                             WHERE old_month.cnt = 1))\n    ),\n    v_old AS (\n        SELECT\n            pr.name,\n            pr.risk,\n            count(pr.name) AS total\n        FROM old_result pr\n        GROUP BY pr.risk, pr.name\n        ORDER BY pr.risk, (count(pr.name)) DESC, pr.name\n    )\nSELECT * FROM v_old WHERE name NOT IN (SELECT name FROM v_new)"
    }
   ]
  },
  {
   "title": "Risk Changes",
   "type": "table",
   "description": "All vulnerabilities detected in scan 1 and scan 2 that had a severity change.",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH primary_time AS (\n--     SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'September' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'September' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$new_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    secondary_time AS (\n--         SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'August' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n--         (SELECT date_trunc('month'::TEXT, (SELECT date_trunc('month'::TEXT, CAST(CONCAT('2020', '-', (SELECT key FROM lookup_values lv INNER JOIN lookup_types lt ON lv.type_id = lt.id WHERE lt.name = 'Months' AND lv.value = 'August' ORDER BY lv.key DESC), '-', '01 00:01:00.000') AS TIMESTAMP)))) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    SELECT\n        date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) AS time_1,\n    (SELECT date_trunc('month'::TEXT, CAST(CONCAT('$year', '-', (SELECT key\n                                                             FROM lookup_values lv\n                                                             INNER JOIN lookup_types lt ON lv.type_id = lt.id\n                                                             WHERE lt.name = 'Months'\n                                                               AND lv.value = '$old_month'\n                                                             ORDER BY lv.key DESC), '-',\n                                              '01 00:01:00.000') AS TIMESTAMP)) + '1 mon'::INTERVAL - '1 day'::INTERVAL AS time_2)\n    ),\n    new_month AS (\n        SELECT\n                row_number()\n                OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n                nessus_scans_info.history_id\n        FROM nessus_scans_info\n        WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n        AND nessus_scans_info.scan_start >= date_trunc('month'::TEXT, (SELECT time_1 FROM primary_time))\n        AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM primary_time)) + '1 mon'::INTERVAL - '1 day'::INTERVAL)\n    ),\n    new_result AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT new_month.history_id FROM new_month WHERE new_month.cnt = 1))\n    ),\n    v_new AS (\n        SELECT\n            nr.name,\n            nr.risk,\n            count(nr.name) AS total\n        FROM new_result nr\n        GROUP BY nr.risk, nr.name\n        ORDER BY nr.risk, (count(nr.name)) DESC, nr.name\n    ),\n    old_month AS (\n        SELECT\n            row_number()\n            OVER (PARTITION BY nessus_scans_info.scan_id ORDER BY nessus_scans_info.scan_start DESC) AS cnt,\n            nessus_scans_info.scan_id,\n            nessus_scans_info.history_id,\n            nessus_scans_info.scan_start,\n            nessus_scans_info.status\n        FROM nessus_scans_info\n        WHERE nessus_scans_info.status::TEXT = 'completed'::TEXT\n        AND nessus_scans_info.scan_start >= (date_trunc('month'::TEXT, (SELECT time_1 FROM secondary_time)) - '1 mon'::INTERVAL)\n        AND nessus_scans_info.scan_start <= (date_trunc('month'::TEXT, (SELECT time_2 FROM secondary_time)) - '1 day'::INTERVAL)\n    ),\n    old_result AS (\n         SELECT DISTINCT\n             nessus_report.host,\n             nessus_report.risk,\n             nessus_report.name\n         FROM nessus_report\n         WHERE (nessus_report.history_id IN (SELECT\n                                                 old_month.history_id\n                                             FROM old_month\n                                             WHERE old_month.cnt = 1))\n    ),\n    v_old AS (\n        SELECT\n            pr.name,\n            pr.risk,\n            count(pr.name) AS total\n        FROM old_result pr\n        GROUP BY pr.risk, pr.name\n        ORDER BY pr.risk, (count(pr.name)) DESC, pr.name\n    )\nSELECT\n    vn.name,\n    vn.risk  AS new_risk,\n    vo.risk AS old_risk,\n    vo.total\nFROM v_new vn\nLEFT JOIN v_old vo ON vn.name = vo.name\nWHERE vo.risk != vn.risk"
    }
   ]
  }
 ]
}